# Generated by Django 5.2.16 on 2026-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_participant_participant_slot_is_first_or_second"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorechange",
            name="reason",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
