# Generated by Django 5.2.16 on 2026-07-18 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, unique=True)),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, '첫 번째'), (2, '두 번째')], unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('slot',),
            },
        ),
        migrations.CreateModel(
            name='RelationshipScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rater', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_score', to='ratings.participant')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_score', to='ratings.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.SmallIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('resulting_score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_changes', to='ratings.participant')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='ratings.relationshipscore')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='relationshipscore',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 100)), name='relationship_score_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='relationshipscore',
            constraint=models.CheckConstraint(condition=models.Q(('rater', models.F('recipient')), _negated=True), name='relationship_score_between_different_participants'),
        ),
        migrations.AddConstraint(
            model_name='scorechange',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='score_change_delta_is_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='scorechange',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_score__gte', 0), ('resulting_score__lte', 100)), name='score_change_result_between_0_and_100'),
        ),
    ]
