# Generated by Django 5.2.16 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0006_rename_domain_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreChangeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="score_change_comments",
                        to="ratings.participant",
                    ),
                ),
                (
                    "score_change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="ratings.scorechange",
                    ),
                ),
            ],
            options={
                "db_table": "score_change_comment",
                "ordering": ("created_at", "pk"),
                "indexes": [
                    models.Index(
                        fields=["score_change", "created_at", "id"],
                        name="score_comment_thread_order_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("content", ""), _negated=True),
                        name="score_change_comment_content_not_empty",
                    ),
                ],
            },
        ),
    ]
