# Generated by Django 5.2.16 on 2026-07-19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0007_scorechangecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorechangecomment",
            name="content",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="scorechangecomment",
            name="media_count",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.RemoveConstraint(
            model_name="scorechangecomment",
            name="score_change_comment_content_not_empty",
        ),
        migrations.AddConstraint(
            model_name="scorechangecomment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("content", ""), _negated=True),
                    ("media_count__gt", 0),
                    _connector="OR",
                ),
                name="score_comment_has_content_or_media",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorechangecomment",
            constraint=models.CheckConstraint(
                condition=models.Q(("media_count__lte", 4)),
                name="score_comment_media_count_at_most_4",
            ),
        ),
        migrations.CreateModel(
            name="MediaAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("score_change", "점수 변경"),
                            ("comment", "댓글"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "이미지"), ("video", "영상")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "업로드 대기"),
                            ("finalizing", "업로드 확인 중"),
                            ("reclaiming", "이전 확인 작업 정리 중"),
                            ("ready", "연결 대기"),
                            ("deleting", "만료 업로드 삭제 중"),
                            ("attached", "연결 완료"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("object_key", models.CharField(max_length=255, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("expected_size", models.PositiveBigIntegerField()),
                (
                    "actual_size",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("etag", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("finalization_token", models.UUIDField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_attachments",
                        to="ratings.scorechangecomment",
                    ),
                ),
                (
                    "score_change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_attachments",
                        to="ratings.scorechange",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_attachments",
                        to="ratings.participant",
                    ),
                ),
            ],
            options={
                "db_table": "media_attachment",
                "ordering": ("position", "created_at", "pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expected_size__gte", 1),
                                ("expected_size__lte", 10485760),
                                ("kind", "image"),
                                ("purpose", "score_change"),
                            ),
                            models.Q(
                                ("expected_size__gte", 1),
                                ("expected_size__lte", 10485760),
                                ("kind", "image"),
                                ("purpose", "comment"),
                            ),
                            models.Q(
                                ("expected_size__gte", 1),
                                ("expected_size__lte", 104857600),
                                ("kind", "video"),
                                ("purpose", "comment"),
                            ),
                            _connector="OR",
                        ),
                        name="media_attachment_purpose_kind_size_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("comment__isnull", True),
                                ("purpose", "score_change"),
                            ),
                            models.Q(
                                ("purpose", "comment"),
                                ("score_change__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="media_attachment_pending_parent_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("comment__isnull", True),
                                ("purpose", "score_change"),
                                ("score_change__isnull", False),
                                ("status", "attached"),
                            ),
                            models.Q(
                                ("comment__isnull", False),
                                ("purpose", "comment"),
                                ("score_change__isnull", False),
                                ("status", "attached"),
                            ),
                            models.Q(
                                ("comment__isnull", True),
                                ("purpose", "score_change"),
                                ("score_change__isnull", True),
                                (
                                    "status__in",
                                    (
                                        "pending",
                                        "finalizing",
                                        "reclaiming",
                                        "ready",
                                        "deleting",
                                    ),
                                ),
                            ),
                            models.Q(
                                ("comment__isnull", True),
                                ("purpose", "comment"),
                                ("score_change__isnull", False),
                                (
                                    "status__in",
                                    (
                                        "pending",
                                        "finalizing",
                                        "reclaiming",
                                        "ready",
                                        "deleting",
                                    ),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="media_attachment_status_parent_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("actual_size__isnull", True),
                                ("finalization_token__isnull", True),
                                ("finalized_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("actual_size__isnull", True),
                                ("finalization_token__isnull", False),
                                ("finalized_at__isnull", True),
                                ("status__in", ("finalizing", "reclaiming")),
                            ),
                            models.Q(
                                ("actual_size__isnull", False),
                                ("finalization_token__isnull", True),
                                ("finalized_at__isnull", False),
                                ("status__in", ("ready", "attached")),
                            ),
                            models.Q(
                                ("actual_size__isnull", True),
                                ("finalized_at__isnull", True),
                                ("status", "deleting"),
                            ),
                            models.Q(
                                ("actual_size__isnull", False),
                                ("finalization_token__isnull", True),
                                ("finalized_at__isnull", False),
                                ("status", "deleting"),
                            ),
                            _connector="OR",
                        ),
                        name="media_attachment_finalization_metadata_valid",
                    ),
                ],
            },
        ),
    ]
