# Generated by Django 5.2.16 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0008_media_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diary_entries",
                        to="ratings.participant",
                    ),
                ),
            ],
            options={
                "db_table": "diary_entry",
                "ordering": ("-created_at", "-pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("content__regex", r"^\s*$"), _negated=True),
                        name="diary_entry_content_not_blank",
                    ),
                ],
            },
        ),
    ]
