# Generated by Django 5.2.16 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0009_diaryentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaattachment",
            name="diary_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_attachments",
                to="ratings.diaryentry",
            ),
        ),
        migrations.AlterField(
            model_name="mediaattachment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("score_change", "점수 변경"),
                    ("comment", "댓글"),
                    ("diary_entry", "공유 일기"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="mediaattachment",
            name="media_attachment_purpose_kind_size_valid",
        ),
        migrations.RemoveConstraint(
            model_name="mediaattachment",
            name="media_attachment_pending_parent_valid",
        ),
        migrations.RemoveConstraint(
            model_name="mediaattachment",
            name="media_attachment_status_parent_valid",
        ),
        migrations.AddConstraint(
            model_name="mediaattachment",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        purpose="score_change",
                        kind="image",
                        expected_size__gte=1,
                        expected_size__lte=10 * 1024 * 1024,
                    )
                    | models.Q(
                        purpose="comment",
                        kind="image",
                        expected_size__gte=1,
                        expected_size__lte=10 * 1024 * 1024,
                    )
                    | models.Q(
                        purpose="comment",
                        kind="video",
                        expected_size__gte=1,
                        expected_size__lte=100 * 1024 * 1024,
                    )
                    | models.Q(
                        purpose="diary_entry",
                        kind="image",
                        expected_size__gte=1,
                        expected_size__lte=10 * 1024 * 1024,
                    )
                    | models.Q(
                        purpose="diary_entry",
                        kind="video",
                        expected_size__gte=1,
                        expected_size__lte=100 * 1024 * 1024,
                    )
                ),
                name="media_attachment_purpose_kind_size_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaattachment",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        purpose="score_change",
                        comment__isnull=True,
                        diary_entry__isnull=True,
                    )
                    | models.Q(
                        purpose="comment",
                        score_change__isnull=False,
                        diary_entry__isnull=True,
                    )
                    | models.Q(
                        purpose="diary_entry",
                        score_change__isnull=True,
                        comment__isnull=True,
                    )
                ),
                name="media_attachment_pending_parent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaattachment",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        status="attached",
                        score_change__isnull=False,
                        purpose="score_change",
                        comment__isnull=True,
                        diary_entry__isnull=True,
                    )
                    | models.Q(
                        status="attached",
                        score_change__isnull=False,
                        purpose="comment",
                        comment__isnull=False,
                        diary_entry__isnull=True,
                    )
                    | models.Q(
                        status="attached",
                        score_change__isnull=True,
                        purpose="diary_entry",
                        comment__isnull=True,
                        diary_entry__isnull=False,
                    )
                    | models.Q(
                        status__in=(
                            "pending",
                            "finalizing",
                            "reclaiming",
                            "ready",
                            "deleting",
                        ),
                        purpose="score_change",
                        score_change__isnull=True,
                        comment__isnull=True,
                        diary_entry__isnull=True,
                    )
                    | models.Q(
                        status__in=(
                            "pending",
                            "finalizing",
                            "reclaiming",
                            "ready",
                            "deleting",
                        ),
                        purpose="comment",
                        score_change__isnull=False,
                        comment__isnull=True,
                        diary_entry__isnull=True,
                    )
                    | models.Q(
                        status__in=(
                            "pending",
                            "finalizing",
                            "reclaiming",
                            "ready",
                            "deleting",
                        ),
                        purpose="diary_entry",
                        score_change__isnull=True,
                        comment__isnull=True,
                        diary_entry__isnull=True,
                    )
                ),
                name="media_attachment_status_parent_valid",
            ),
        ),
    ]
