# Generated by Django 5.2.16 on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0010_diary_entry_media_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diary_entry_comments",
                        to="ratings.participant",
                    ),
                ),
                (
                    "diary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ratings.diaryentry",
                    ),
                ),
            ],
            options={
                "db_table": "diary_entry_comment",
                "ordering": ("created_at", "pk"),
                "indexes": [
                    models.Index(
                        fields=["diary_entry", "created_at", "id"],
                        name="diary_comment_thread_order_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("content__regex", r"^\s*$"),
                            _negated=True,
                        ),
                        name="diary_comment_content_not_blank",
                    ),
                ],
            },
        ),
    ]
